### PR TITLE
[DNM] Test

### PR DESCRIPTION
**Pull request by piyush1594**

### CODE REVIEW

**Comment by gabemontero** [comment]
I probably need a little more context or description of the entire flow @piyush1594 
Based on the files you changed I'm not sure how PRs comes into the picture.

Also there are concurrent builds in Jenkins and concurrent builds in OpenShift  ... some of the jobs you have modified are doing both, and you would need to manage the openshift side settings ... see https://docs.openshift.com/container-platform/3.4/dev_guide/builds/build_run_policy.html#build-parallel-run-policy

Otherwise, I'm not very familiar with concurrent running jobs in Jenkins.  If more is involved besides the config setting you've removed, I'm unaware.

**Comment by piyush1594** [comment]
@gabemontero I am trying to figure out where this property is getting configured https://github.com/jenkinsci/workflow-job-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProperty.java

**Comment by gabemontero** [comment]
On Mon, Jul 30, 2018 at 9:57 AM, Piyush Garg <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> I am trying to figure out
> where this property is getting configured https://github.com/jenkinsci/
> workflow-job-plugin/blob/master/src/main/java/org/
> jenkinsci/plugins/workflow/job/properties/DisableConcurrentBuildsJobProp
> erty.java
>
ah, ok; yeah, that is down in the core workflow plugin support;

not familiar with how that happens offhand;  I can see about exploring that
code base and bit and see, but
I've got some customer and QE support items I need to square first;  won't
be until later today or Tuesday
before I can spend some cycles on that

**Comment by piyush1594** [comment]
@gabemontero Can you give me some pointers like where that is getting configured in our case, I will do the rest of the work for the time being

**Comment by gabemontero** [comment]
On Mon, Jul 30, 2018 at 10:58 AM, Piyush Garg <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> Can you give me some
> pointers like where that is getting configured in our case, I will do the
> rest of the work for the time being
>
Couldn't find anything the explicitly is manipulating this.

My only suggestion is to rebuild the workflow-job plugin, and at the top of
this method:
https://github.com/jenkinsci/workflow-job-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/job/WorkflowJob.java#L358-L378

Add:

Exception e = new Exception("disable concurrent called");
LOGGER.log(Level.INFO, "", e);

and see if you get any calls to it reported in the jenkins log.

**Comment by piyush1594** [comment]
Closing it, not relevant

**Pull request closed without merging**
