### PR TITLE
follow up commits

### PR DESCRIPTION
**Pull request by edewit**
as discussed on #15

### CODE REVIEW

**Comment by edewit** [comment]
@jaseemabid the make file created this Dockerfile.version btw maybe we should add it to .gitignore?

**Comment by jaseemabid** [comment]
@edewit Looks like the build script was supposed to delete the file, but it didn't. Ideally debug the script and fix it, or just add it to .gitignore for now.

PS: I'll check what the upstream is doing, because this is an old messy fork at this moment.

**Comment by gastaldi** [comment]
Is it possible to somehow use the [official repo](https://github.com/openshift/jenkins) and avoid this fork?

**Comment by jaseemabid** [comment]
@gastaldi I've been looking at it for a while. Hopefully before GA we will be able to do it. Someone needs to take a deep look at what changed, and _**test**_ the changes before we throw this away.

**Comment by jaseemabid** [comment]
I'm merging this, its only changes that we discussed in the previous PR.

**Pull request merged**
