### PR TITLE
chore updated oc client from 1.4 to 3.6

### PR DESCRIPTION
**Pull request by edewit**
using yum instead of curl

### CODE REVIEW

**Comment by rupalibehera** [comment]
I am merging this , lets test this on the tenant once it raises PR https://github.com/fabric8io/openshift-jenkins-s2i-config. if it works good, if we face issues need to revert this commit.

**Comment by jaseemabid** [comment]
@edewit Should't you yum install before yum clean to speed things up a bit? 

The version 1 is probably way too outdated now and can be ignored. At least we don't use it anywhere.

**Comment by jaseemabid** [comment]
@edewit Why are we adding a new `1/Dockerfile.version` file?

**Comment by jaseemabid** [comment]
@edewit Could you please raise another PR with

1. Deleting the extra file 
2. Calling `yum clean` after all the other yum commands like it used to be?

**Pull request merged**
